name: echo-app
metadata:
  template: echo-app@0.0.1

# Environment definitions
environments:
  dev:
    infra:
      parameters: infra/environments/dev.parameters.json
  staging:
    infra:
      parameters: infra/environments/staging.parameters.json
  prod:
    infra:
      parameters: infra/environments/prod.parameters.json

services:
  backend:
    project: ./backend
    language: python
    host: containerapp
    docker:
      path: ./Dockerfile
      context: .

  frontend:
    project: ./frontend
    language: js
    host: containerapp
    docker:
      path: ./Dockerfile
      context: .
      buildArgs:
        # Note: No VITE_API_URL needed - frontend uses /api proxy to internal backend
        - VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID}
        - VITE_TENANT_ID=${VITE_TENANT_ID}
        - VITE_API_SCOPE=${VITE_API_SCOPE}

hooks:
  preprovision:
    windows:
      shell: pwsh
      run: ./infra/hooks/preprovision.ps1
    posix:
      shell: sh
      run: ./infra/hooks/preprovision.sh

  postprovision:
    windows:
      shell: pwsh
      run: ./infra/hooks/postprovision.ps1
    posix:
      shell: sh
      run: ./infra/hooks/postprovision.sh

# Pipeline configuration
# CI/CD setup is handled separately from Azure infrastructure provisioning.
# After running 'azd up', configure GitHub Actions by running:
#   ./scripts/ci/setup_github_cicd.sh
#
# This separation ensures:
#   - 'azd up' only handles Azure infrastructure and app registrations
#   - CI/CD configuration is explicitly managed via the setup script
pipeline:
  provider: github
