#!/bin/bash

# Echo App - Manual Setup & Run Script
# =====================================
# This script sets up and runs the Echo App locally without Docker.
#
# Prerequisites:
#   - Node.js 20+
#   - Python 3.12+
#   - uv (https://docs.astral.sh/uv/)
#
# Optional (for Entra auth):
#   - Azure CLI (az)
#   - Run ./scripts/auth/setup_local_auth.sh to create app registrations
#
# Usage:
#   ./scripts/dev/manual_setup.sh           # Start with auth disabled (default)
#   ./scripts/dev/manual_setup.sh --auth    # Start with auth enabled (requires setup_local_auth.sh first)

set -e

# Anchor to repo root so the script works from anywhere
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════╗"
echo "║       Echo App - Local Development        ║"
echo "╚═══════════════════════════════════════════╝"
echo -e "${NC}"

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js 20+ and try again."
    echo "   https://nodejs.org/"
    exit 1
fi
echo "✓ Node.js $(node --version)"

if ! command -v uv &> /dev/null; then
    echo "❌ uv is not installed. Please install uv and try again."
    echo "   https://docs.astral.sh/uv/"
    exit 1
fi
echo "✓ uv $(uv --version | head -1)"

echo ""

# ============================================
# Setup Backend Environment
# ============================================
echo "Setting up backend environment..."

if [ ! -f "$REPO_ROOT/backend/.env" ]; then
    echo "Creating backend/.env from template..."
    cat > "$REPO_ROOT/backend/.env" << 'EOF'
# Backend Local Development Configuration
# ===========================================
# Generated by manual_setup.sh

# Authentication (disabled by default)
AUTH_ENABLED=false
AZURE_TENANT_ID=
AZURE_API_SCOPE=
AZURE_API_APP_ID=

# Cosmos DB Emulator (requires: docker compose up cosmosdb)
COSMOS_EMULATOR=true
COSMOS_DB_NAME=echoapp
COSMOS_DECKS_CONTAINER=decks
COSMOS_CARDS_CONTAINER=cards

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost
EOF
    echo "✓ Created backend/.env"
else
    echo "✓ backend/.env exists"
fi

# ============================================
# Setup Frontend Environment
# ============================================
echo "Setting up frontend environment..."

if [ ! -f "$REPO_ROOT/frontend/.env.local" ]; then
    echo "Creating frontend/.env.local from template..."
    cat > "$REPO_ROOT/frontend/.env.local" << 'EOF'
# Frontend Local Development Configuration
# ===========================================
# Generated by manual_setup.sh

# Authentication (disabled by default)
VITE_AUTH_ENABLED=false
VITE_AZURE_CLIENT_ID=
VITE_TENANT_ID=
VITE_API_SCOPE=
EOF
    echo "✓ Created frontend/.env.local"
else
    echo "✓ frontend/.env.local exists"
fi

# ============================================
# Handle --auth flag
# ============================================
if [ "${1:-}" == "--auth" ]; then
    echo ""
    echo -e "${YELLOW}Authentication mode requested${NC}"
    
    # Check if auth is configured
    if grep -q "^VITE_AZURE_CLIENT_ID=.\+" "$REPO_ROOT/frontend/.env.local" 2>/dev/null; then
        echo "✓ Auth configuration found"
        
        # Enable auth in both files
        sed -i.bak 's/^AUTH_ENABLED=.*/AUTH_ENABLED=true/' "$REPO_ROOT/backend/.env"
        sed -i.bak 's/^VITE_AUTH_ENABLED=.*/VITE_AUTH_ENABLED=true/' "$REPO_ROOT/frontend/.env.local"
        rm -f "$REPO_ROOT/backend/.env.bak" "$REPO_ROOT/frontend/.env.local.bak"
        
        echo "✓ Auth enabled in environment files"
    else
        echo ""
        echo "❌ Auth is not configured. Please run first:"
        echo ""
        echo "   ./scripts/auth/setup_local_auth.sh"
        echo ""
        echo "Then try again with: ./scripts/dev/manual_setup.sh --auth"
        exit 1
    fi
fi

echo ""

# ============================================
# Install Dependencies
# ============================================
echo "Installing dependencies..."

echo "📦 Backend (Python)..."
cd "$REPO_ROOT/backend"
uv sync --quiet
echo "✓ Backend dependencies installed"

echo "📦 Frontend (Node.js)..."
cd "$REPO_ROOT/frontend"
npm install --silent
echo "✓ Frontend dependencies installed"

cd "$REPO_ROOT"

# ============================================
# Start Services
# ============================================
echo ""
echo "Starting services..."

# Check for Cosmos DB emulator
COSMOS_EMULATOR=$(grep "^COSMOS_EMULATOR=" "$REPO_ROOT/backend/.env" | cut -d'=' -f2)
if [ "$COSMOS_EMULATOR" == "true" ]; then
    # Check if emulator is running
    if ! curl -k -s https://localhost:8081/_explorer/emulator.pem > /dev/null 2>&1; then
        echo ""
        echo -e "${YELLOW}⚠ Cosmos DB Emulator is not running${NC}"
        echo ""
        echo "Start the emulator with:"
        echo "  docker compose up cosmosdb -d"
        echo ""
        echo "Or set COSMOS_EMULATOR=false in backend/.env to use Azure Cosmos DB"
        echo "(requires: az login)"
        echo ""
        read -p "Continue without Cosmos DB? (y/N) " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    else
        echo "✓ Cosmos DB Emulator is running"
    fi
fi

# Start backend
echo ""
echo "🔧 Starting backend on http://localhost:8000..."
cd "$REPO_ROOT/backend"
uv run uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!

# Start frontend
echo "🎨 Starting frontend on http://localhost:5173..."
cd "$REPO_ROOT/frontend"
npm run dev &
FRONTEND_PID=$!

# Trap to clean up on exit
cleanup() {
    echo ""
    echo "🛑 Shutting down..."
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    exit 0
}
trap cleanup SIGINT SIGTERM

# Wait for services to start
sleep 3

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════╗"
echo "║           Echo App is running!            ║"
echo "╚═══════════════════════════════════════════╝${NC}"
echo ""
echo "  Frontend: http://localhost:5173"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo ""

AUTH_ENABLED=$(grep "^AUTH_ENABLED=" "$REPO_ROOT/backend/.env" | cut -d'=' -f2)
if [ "$AUTH_ENABLED" == "true" ]; then
    echo "  🔐 Authentication: ENABLED (Entra ID)"
else
    echo "  🔓 Authentication: DISABLED (dev mode)"
    echo ""
    echo "  To enable Entra auth, run: ./scripts/auth/setup_local_auth.sh"
fi

echo ""
echo "Press Ctrl+C to stop both services."
echo ""

# Wait for both processes
wait
